modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="fundys_cursed_food"
version="1.0.4.1"
displayName="Fundy's Cursed Food"
credits="Source code: https://github.com/Piseks-Mods/Fundys-Cursed-Food-Forge/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fundys-cursed-food"
logoFile="logo.png"
authors="Písek Pískovec"
description='''
Fundy's Cursed Food from his video
'''

[[dependencies.fundys_cursed_food]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




